import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });
import 'react-toastify/dist/ReactToastify.css';
export const metadata: Metadata = {
  title: "Shop Figure",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="text-white w-screen bg-[#ebebeb]" lang="en">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
